USE [EXACTUS]
GO
/****** Object:  StoredProcedure [fnica].[uspFAFImprimirFacturaImpresor]    Script Date: 26/01/2023 11:54:25 a. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [fnica].[uspFAFImprimirFacturaImpresor]
@sucursal AS nvarchar(4), @numero AS nvarchar(10),@Impresa AS int ,@ImprimeLote as int = NULL
AS
BEGIN

if @ImprimeLote is null
	set @ImprimeLote=0


IF ( @Impresa=1)
BEGIN
		
	SELECT  A.CODSUCURSAL,B.SUCURSAL, A.TIPO, A.TIPOFORMATO, A.FACTURA, A.FECHAFACTURA, A.CODCLIENTE, upper(A.CLIENTE) CLIENTE, A.FECHAVENCIMIENTO, A.CODVENDEDOR,C.NOMBRESVENDEDOR + ' ' + C.APELLIDOSVENDEDOR NOMBREVENDEDOR, A.REMISION, 
						  A.TIPOPAGO,d.DESCRIPCION DESCRTIPOPAGO, A.SUBTOTAL, A.DESCUENTO, A.IVA, A.TOTALFACTURA,A.TIPOCAMBIO, fnica.zNumberToLetters(A.TOTALFACTURA) AS Expr1,p.NumAutorizadoDGI,
						  UPPER(CL.NOMBRESCLIENTE + ' ' + CL.APELLIDOSCLIENTE) NOMBRECLIENTE,CL.AllowEditName ,fnica.zNumberToLetters((A.TOTALFACTURA + ISNULL(A.MontoFlete,0))/A.TIPOCAMBIO) AS MontoLetrasDolar, fnica.globalGetUltTasadeCompra(FechaFactura) TipoCambioParalelo,ISNULL(A.MontoFlete,0) MontoFlete
	FROM         fnica.fafFACTURA A
	INNER JOIN FNICA.globalSUCURSALES B ON B.CODSUCURSAL = A.CODSUCURSAL
	INNER JOIN FNICA.globalVENDEDORES C ON A.CODVENDEDOR= C.CODVENDEDOR  AND A.CODSUCURSAL=C.CODSUCURSAL
	INNER JOIN FNICA.ccfCLIENTES CL ON A.CODCLIENTE=CL.CODCLIENTE
	INNER JOIN fnica.fafTIPOSPAGO d ON a.TIPOPAGO=d.TIPOPAGO
	inner  join (select @Sucursal CodSucursal, NumAutorizadoDGI    FROM fnica.fafParametrosGenerales)  P on A.codsucursal= P.CodSucursal 
	WHERE     (A.CODSUCURSAL = @sucursal) AND  (A.FACTURA = @numero) 

if (@ImprimeLote=1)
	begin	
		SELECT   sum(CANTIDAD)CANTIDAD,avg(PRECIOUNITARIO)PRECIOUNITARIO,sum(SUBTOTAL)SUBTOTAL,SUM( DESCUENTO)DESCUENTO,sum(IVA)IVA,
		SUM( TOTAL)TOTAL, CODCULTIVO, NUMEROSERIE,a.ARTICULO, b.DESCRIPCION , 
							  b.UNIDAD_ALMACEN, b.FACTOR_EMPAQUE,a.LOTE
		FROM         fnica.fafFACTURADETALLE a INNER JOIN fnica.vPRODUCTOS b ON a.ARTICULO = b.PRODUCTO
		WHERE     (CODSUCURSAL = @sucursal)  AND (FACTURA = @numero) 
		group by CODCULTIVO, NUMEROSERIE,a.ARTICULO, b.DESCRIPCION,b.UNIDAD_ALMACEN, b.FACTOR_EMPAQUE,a.LOTE
	end
else
	begin
	--FacturaDetalle
		SELECT CANTIDAD,PRECIOUNITARIO,SUBTOTAL,DESCUENTO,IVA,TOTAL,CODCULTIVO,NUMEROSERIE,ARTICULO,Combo,DESCRIPCION,UNIDAD_ALMACEN,FACTOR_EMPAQUE,Lote
		FROM 
		(
			--SELECT   sum(CANTIDAD)CANTIDAD,
			SELECT
			sum(CANTIDAD) CANTIDAD, --CASE WHEN COMBO IS NULL THEN  sum(CANTIDAD)  ELSE 0 END CANTIDAD,
			CASE WHEN COMBO IS NULL THEN avg(PRECIOUNITARIO)  ELSE 0 END PRECIOUNITARIO,
			CASE WHEN COMBO IS NULL THEN sum(SUBTOTAL)ELSE 0 END SUBTOTAL,
			CASE WHEN COMBO IS NULL THEN SUM( DESCUENTO)ELSE 0 END DESCUENTO,
			CASE WHEN COMBO IS NULL THEN sum(IVA)ELSE 0 END IVA,
			CASE WHEN COMBO IS NULL THEN SUM( TOTAL)ELSE 0 END TOTAL,
			CODCULTIVO, NUMEROSERIE,
			a.ARTICULO,
			A.Combo,
			CASE WHEN COMBO IS NULL THEN B.DESCRIPCION ELSE '     '+B.DESCRIPCION END DESCRIPCION,
			b.UNIDAD_ALMACEN, b.FACTOR_EMPAQUE,'' Lote,
			CASE WHEN COMBO IS NULL THEN 0  ELSE 2 END Nivel 
			FROM         fnica.fafFACTURADETALLE a INNER JOIN fnica.vPRODUCTOS b ON a.ARTICULO = b.PRODUCTO
			WHERE     (CODSUCURSAL = @sucursal)  AND (FACTURA = @numero)  
			group by CODCULTIVO, NUMEROSERIE,a.ARTICULO, b.DESCRIPCION,A.COMBO,B.UNIDAD_ALMACEN, b.FACTOR_EMPAQUE
			UNION ALL
			select y.CANTIDAD,(x.PRECIOUNITARIO/y.Cantidad) PRECIOUNITARIO,x.SUBTOTAL,x.DESCUENTO,x.IVA,x.TOTAL,'' CODCULTIVO,'' NUMEROSERIE, x.Combo ARTICULO,x.Combo COMBO,
			y.Descr DESCRIPCION, 'UND' UNIDAD_ALMACEN,1 FACTOR_EMPAQUE,'' LOTE,1 Nivel
			from 
			(
				select CODSUCURSAL,factura,CODCLIENTE,Combo,SUM(CANTIDAD)CANTIDAD, sum(PRECIOUNITARIO*CANTIDAD) PRECIOUNITARIO,SUM(SUBTOTAL) SUBTOTAL,
				SUM(IVA) IVA,SUM(TOTAL)TOTAL,sum(DESCUENTO) DESCUENTO
				from fnica.fafFACTURADETALLE 
				where factura=@numero and CODSUCURSAL=@sucursal and Not (Combo is null)
				group by CODSUCURSAL,factura,CODCLIENTE,Combo
			)x inner join 
			(
				SELECT a.CODSUCURSAL,a.factura,a.IDCombo,a.Cantidad,b.Articulo combo,b.Descr FROM 
				fnica.fafFACTURADETALLECombo a inner join fnica.fafCombo b on a.IDCombo=b.IDCombo
				WHERE factura=@numero and CODSUCURSAL=@sucursal

			)
			 y on x.codsucursal=y.codsucursal and x.factura=y.factura and x.combo=y.combo
			)Z ORDER BY Z.COMBO,z.Nivel
	
	end
END



-- aqui va a la temporal
ELSE
BEGIN			
	SELECT  A.CODSUCURSAL,B.SUCURSAL, A.TIPO, A.TIPOFORMATO, A.FACTURA, A.FECHAFACTURA, A.CODCLIENTE, UPPER(A.CLIENTE) CLIENTE, A.FECHAVENCIMIENTO, A.CODVENDEDOR,C.NOMBRESVENDEDOR + ' ' + C.APELLIDOSVENDEDOR NOMBREVENDEDOR, A.REMISION, 
						  A.TIPOPAGO ,d.DESCRIPCION DESCRTIPOPAGO, A.SUBTOTAL, A.DESCUENTO, A.IVA, A.TOTALFACTURA,A.TIPOCAMBIO, fnica.zNumberToLetters(A.TOTALFACTURA) AS Expr1,p.NumAutorizadoDGI,
						  UPPER(CL.NOMBRESCLIENTE + ' ' + CL.APELLIDOSCLIENTE) NOMBRECLIENTE,CL.AllowEditName,fnica.zNumberToLetters((A.TOTALFACTURA + ISNULL(A.MontoFlete,0)) /A.TIPOCAMBIO) AS MontoLetrasDolar ,fnica.globalGetUltTasadeCompra(FechaFactura) TipoCambioParalelo,ISNULL(MontoFlete,0) MontoFlete
	FROM         fnica.tmpImpresionfafFACTURA A
	INNER JOIN FNICA.globalSUCURSALES B ON B.CODSUCURSAL = A.CODSUCURSAL
	INNER JOIN FNICA.globalVENDEDORES C ON A.CODVENDEDOR= C.CODVENDEDOR  AND A.CODSUCURSAL=C.CODSUCURSAL
	INNER JOIN fnica.fafTIPOSPAGO d ON a.TIPOPAGO=d.TIPOPAGO
	INNER JOIN FNICA.ccfCLIENTES CL ON A.CODCLIENTE=CL.CODCLIENTE
	inner  join (select @Sucursal CodSucursal, NumAutorizadoDGI    FROM fnica.fafParametrosGenerales)  P on A.codsucursal= P.CodSucursal 
	WHERE     (A.CODSUCURSAL = @sucursal) AND  (A.FACTURA = @numero) 
	--tmpImpresorFacturaDetalle
		SELECT CANTIDAD,PRECIOUNITARIO,SUBTOTAL,DESCUENTO,IVA,TOTAL,CODCULTIVO,NUMEROSERIE,ARTICULO,Combo,DESCRIPCION,UNIDAD_ALMACEN,FACTOR_EMPAQUE,Lote
		FROM 
		(
			SELECT   
			sum(CANTIDAD) CANTIDAD ,--CASE WHEN COMBO IS NULL THEN  sum(CANTIDAD)  ELSE 0 END CANTIDAD,
			CASE WHEN COMBO IS NULL THEN avg(PRECIOUNITARIO)  ELSE 0 END PRECIOUNITARIO,
			CASE WHEN COMBO IS NULL THEN sum(SUBTOTAL)ELSE 0 END SUBTOTAL,
			CASE WHEN COMBO IS NULL THEN SUM( DESCUENTO)ELSE 0 END DESCUENTO,
			CASE WHEN COMBO IS NULL THEN sum(IVA)ELSE 0 END IVA,
			CASE WHEN COMBO IS NULL THEN SUM( TOTAL)ELSE 0 END TOTAL,
			CODCULTIVO, NUMEROSERIE,
			a.ARTICULO,
			A.Combo,
			CASE WHEN COMBO IS NULL THEN B.DESCRIPCION ELSE '     '+B.DESCRIPCION END DESCRIPCION,
			b.UNIDAD_ALMACEN, b.FACTOR_EMPAQUE,'' Lote,
			CASE WHEN COMBO IS NULL THEN 0  ELSE 2 END Nivel 
			FROM         fnica.tmpImpresionfafFACTURADETALLE a INNER JOIN fnica.vPRODUCTOS b ON a.ARTICULO = b.PRODUCTO
			WHERE     (CODSUCURSAL = @sucursal)  AND (FACTURA = @numero)  
			group by CODCULTIVO, NUMEROSERIE,a.ARTICULO, b.DESCRIPCION,A.COMBO,B.UNIDAD_ALMACEN, b.FACTOR_EMPAQUE
			UNION ALL
			select y.CANTIDAD,(x.PRECIOUNITARIO/y.Cantidad) PRECIOUNITARIO,x.SUBTOTAL,x.DESCUENTO,x.IVA,x.TOTAL,'' CODCULTIVO,'' NUMEROSERIE, x.Combo ARTICULO,x.Combo COMBO,
			y.Descr DESCRIPCION, 'UND' UNIDAD_ALMACEN,1 FACTOR_EMPAQUE,'' LOTE,1 Nivel
			from 
			(
				select CODSUCURSAL,factura,CODCLIENTE,Combo,SUM(CANTIDAD)CANTIDAD, sum(PRECIOUNITARIO*CANTIDAD) PRECIOUNITARIO,SUM(SUBTOTAL) SUBTOTAL,
				SUM(IVA) IVA,SUM(TOTAL)TOTAL,sum(DESCUENTO) DESCUENTO
				from fnica.tmpImpresionfafFACTURADETALLE 
				where factura=@numero and CODSUCURSAL=@sucursal and Not (Combo is null)
				group by CODSUCURSAL,factura,CODCLIENTE,Combo
			)x inner join 
			(
				SELECT a.CODSUCURSAL,a.factura,a.IDCombo,a.Cantidad,b.Articulo combo,b.Descr FROM 
				fnica.fafFACTURADETALLECombo a inner join fnica.fafCombo b on a.IDCombo=b.IDCombo
				WHERE factura=@numero and CODSUCURSAL=@sucursal

			)
			 y on x.codsucursal=y.codsucursal and x.factura=y.factura and x.combo=y.combo
			)Z ORDER BY Z.COMBO,z.Nivel
		

END

SELECT FormatoFactura FROM fnica.globalSUCURSALES WHERE CODSUCURSAL=@sucursal



SELECT a.Promocion1 + a.Promocion2 PromocionLocal,b.PromocionLocal PromocionNacional,a.AplicaPromocionNacional,a.AplicaPromocionLocal
  FROM fnica.globalSUCURSALES a
  INNER JOIN (SELECT @sucursal sucursal ,promocion1 + ' ' + promocion2 PromocionLocal FROM fnica.fafParametrosGenerales) B
  ON a.CODSUCURSAL=b.SUCURSAL
WHERE CODSUCURSAL=@sucursal
  	         
END

